# Generated by Django 5.2.1 on 2025-05-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_question_type_survey_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_number',
            field=models.CharField(default=11, max_length=3),
            preserve_default=False,
        ),
    ]
