# Generated by Django 5.2.1 on 2025-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_option_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_number',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='option_number',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
