# Generated by Django 5.2.1 on 2025-05-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_question_option_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='option_number',
            field=models.IntegerField(max_length=3),
        ),
    ]
