# Generated by Django 5.2.1 on 2025-05-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_responsesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='survey',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.responsesession'),
            preserve_default=False,
        ),
    ]
