# Generated by Django 5.2.1 on 2025-05-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_userresponse_survey_userresponse_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='session',
            new_name='session_id',
        ),
    ]
