# Generated by Django 5.2.1 on 2025-05-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_session_userresponse_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
