# Generated by Django 5.2.1 on 2025-05-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_assignedsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedsurvey',
            name='completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
